-- ============================================================
-- GymFlow — Seed unificado: todos os exercícios globais
-- Combina os batches originais (003, 009, 018) em um só arquivo.
-- Usa WHERE NOT EXISTS para ser idempotente.
-- ============================================================
insert into exercises (name, name_pt, muscle_groups, equipment, difficulty, is_global)
select v.name, v.name_pt, v.muscle_groups, v.equipment, v.difficulty::exercise_difficulty, true
from (values

-- ► PEITO
('Barbell Bench Press',        'Supino Reto com Barra',              array['Peito','Tríceps','Ombros'],            array['Barra','Banco'],          'intermediate'),
('Incline Dumbbell Press',     'Supino Inclinado com Halteres',      array['Peito','Ombros'],                      array['Halteres','Banco'],       'intermediate'),
('Cable Crossover',            'Crucifixo no Cabo',                  array['Peito'],                               array['Cabo'],                   'intermediate'),
('Push-up',                    'Flexão de Braço',                    array['Peito','Tríceps','Ombros'],            array['Peso Corporal'],          'beginner'),
('Dumbbell Fly',               'Crucifixo com Halteres',             array['Peito'],                               array['Halteres','Banco'],       'beginner'),
('Decline Bench Press',        'Supino Declinado com Barra',         array['Peito','Tríceps'],                     array['Barra','Banco'],          'intermediate'),
('Close-Grip Bench Press',     'Supino Fechado com Barra',           array['Tríceps','Peito'],                     array['Barra','Banco'],          'intermediate'),
('Pec Deck',                   'Peck Deck (Máquina)',                array['Peito'],                               array['Máquina'],                'beginner'),
('High Cable Crossover',       'Crossover Cabo Alto',                array['Peito'],                               array['Cabo'],                   'beginner'),
('Low Cable Crossover',        'Crossover Cabo Baixo',               array['Peito'],                               array['Cabo'],                   'beginner'),
('Dumbbell Pullover',          'Pullover com Haltere',               array['Peito','Costas'],                      array['Halteres','Banco'],       'intermediate'),
('Incline Push-up',            'Flexão Inclinada',                   array['Peito','Tríceps','Ombros'],            array['Peso Corporal'],          'beginner'),
('Decline Push-up',            'Flexão Declinada',                   array['Peito','Ombros'],                      array['Peso Corporal'],          'intermediate'),
('Floor Press',                'Supino no Chão',                     array['Peito','Tríceps'],                     array['Barra'],                  'intermediate'),
('Svend Press',                'Svend Press',                        array['Peito'],                               array['Anilhas'],                'beginner'),
('Landmine Press',             'Press no Landmine',                  array['Peito','Ombros'],                      array['Barra'],                  'intermediate'),
('Smith Machine Bench Press',  'Supino no Smith',                    array['Peito','Tríceps','Ombros'],            array['Smith'],                  'beginner'),
('Cable Fly',                  'Crucifixo no Cabo (altura média)',   array['Peito'],                               array['Cabo'],                   'beginner'),
('Squeeze Press',              'Supino com Contração (Halteres)',    array['Peito'],                               array['Halteres'],               'beginner'),

-- ► COSTAS
('Pull-up',                    'Barra Fixa',                         array['Costas','Bíceps'],                     array['Barra Fixa'],             'intermediate'),
('Barbell Row',                'Remada Curvada com Barra',           array['Costas','Bíceps'],                     array['Barra'],                  'intermediate'),
('Lat Pulldown',               'Puxada no Pulley',                   array['Costas','Bíceps'],                     array['Máquina','Cabo'],         'beginner'),
('Seated Cable Row',           'Remada Sentada no Cabo',             array['Costas','Bíceps'],                     array['Cabo','Máquina'],         'beginner'),
('Deadlift',                   'Levantamento Terra',                 array['Costas','Lombar','Glúteos','Isquiotibiais'], array['Barra'],           'advanced'),
('Single-arm Dumbbell Row',    'Remada Unilateral com Haltere',      array['Costas','Bíceps'],                     array['Halteres','Banco'],       'beginner'),
('T-Bar Row',                  'Remada no Cavalinho',                array['Costas','Bíceps'],                     array['Barra'],                  'intermediate'),
('Chest-Supported Row',        'Remada Apoiada no Banco',            array['Costas','Bíceps'],                     array['Halteres','Banco'],       'beginner'),
('Straight-Arm Pulldown',      'Puxada de Braço Reto',               array['Costas'],                              array['Cabo'],                   'beginner'),
('Hyperextension',             'Hiperextensão Lombar',               array['Lombar','Glúteos'],                    array['Máquina'],                'beginner'),
('Good Morning',               'Bom Dia com Barra',                  array['Lombar','Isquiotibiais'],              array['Barra'],                  'intermediate'),
('Chin-up',                    'Barra Fixa Supinada',                array['Costas','Bíceps'],                     array['Barra Fixa'],             'intermediate'),
('Meadows Row',                'Remada Meadows',                     array['Costas','Bíceps'],                     array['Barra'],                  'intermediate'),
('Face Pull Rope',             'Face Pull com Corda',                array['Ombros','Trapézio','Costas'],          array['Cabo'],                   'beginner'),
('Pendlay Row',                'Remada Pendlay',                     array['Costas','Bíceps'],                     array['Barra'],                  'intermediate'),
('Yates Row',                  'Remada Yates',                       array['Costas','Bíceps'],                     array['Barra'],                  'intermediate'),
('Trap Bar Deadlift',          'Terra com Barra Hexagonal',          array['Costas','Quadríceps','Glúteos'],       array['Barra Hexagonal'],        'intermediate'),
('Rack Pull',                  'Terra no Rack',                      array['Costas','Lombar','Trapézio'],          array['Barra'],                  'intermediate'),
('Seated Machine Row',         'Remada Máquina Sentado',             array['Costas','Bíceps'],                     array['Máquina'],                'beginner'),
('Cable Pull-Through',         'Pull-Through no Cabo',               array['Glúteos','Isquiotibiais','Lombar'],    array['Cabo'],                   'beginner'),
('Jefferson Curl',             'Jefferson Curl',                     array['Lombar','Isquiotibiais'],              array['Halteres'],               'advanced'),
('Barbell Shrug',              'Encolhimento de Ombros com Barra',   array['Trapézio'],                            array['Barra'],                  'beginner'),
('Dumbbell Shrug',             'Encolhimento de Ombros com Haltere', array['Trapézio'],                            array['Halteres'],               'beginner'),

-- ► OMBROS
('Overhead Press',             'Desenvolvimento com Barra',          array['Ombros','Tríceps'],                    array['Barra'],                  'intermediate'),
('Dumbbell Lateral Raise',     'Elevação Lateral com Halteres',      array['Ombros'],                              array['Halteres'],               'beginner'),
('Face Pull',                  'Face Pull',                          array['Ombros','Trapézio'],                   array['Cabo'],                   'beginner'),
('Arnold Press',               'Desenvolvimento Arnold',             array['Ombros','Tríceps'],                    array['Halteres'],               'intermediate'),
('Dumbbell Front Raise',       'Elevação Frontal com Halteres',      array['Ombros'],                              array['Halteres'],               'beginner'),
('Barbell Upright Row',        'Remada Alta com Barra',              array['Ombros','Trapézio'],                   array['Barra'],                  'intermediate'),
('Shoulder Shrug',             'Encolhimento de Ombros',             array['Trapézio'],                            array['Halteres'],               'beginner'),
('Reverse Pec Deck',           'Voador Invertido (Máquina)',         array['Ombros','Trapézio'],                   array['Máquina'],                'beginner'),
('Cable Lateral Raise',        'Elevação Lateral no Cabo',           array['Ombros'],                              array['Cabo'],                   'beginner'),
('Single-arm Overhead Press',  'Desenvolvimento Unilateral',         array['Ombros','Tríceps'],                    array['Halteres'],               'intermediate'),
('Pike Push-up',               'Flexão em Pike',                     array['Ombros','Tríceps'],                    array['Peso Corporal'],          'intermediate'),
('Machine Shoulder Press',     'Desenvolvimento na Máquina',         array['Ombros','Tríceps'],                    array['Máquina'],                'beginner'),
('Smith Shoulder Press',       'Desenvolvimento no Smith',           array['Ombros','Tríceps'],                    array['Smith'],                  'beginner'),
('Cable Front Raise',          'Elevação Frontal no Cabo',           array['Ombros'],                              array['Cabo'],                   'beginner'),
('Bent-over Lateral Raise',    'Elevação Lateral Inclinado',         array['Ombros','Trapézio'],                   array['Halteres'],               'beginner'),
('Landmine Lateral Raise',     'Elevação Lateral no Landmine',       array['Ombros'],                              array['Barra'],                  'intermediate'),
('Push Press',                 'Push Press',                         array['Ombros','Tríceps','Quadríceps'],       array['Barra'],                  'intermediate'),
('Seated Dumbbell Press',      'Desenvolvimento com Haltere Sentado',array['Ombros','Tríceps'],                    array['Halteres','Banco'],       'beginner'),

-- ► BÍCEPS
('Barbell Curl',               'Rosca Direta com Barra',             array['Bíceps'],                              array['Barra'],                  'beginner'),
('Incline Dumbbell Curl',      'Rosca Inclinada com Halteres',       array['Bíceps'],                              array['Halteres','Banco'],       'beginner'),
('Hammer Curl',                'Rosca Martelo',                      array['Bíceps','Antebraços'],                 array['Halteres'],               'beginner'),
('Cable Curl',                 'Rosca no Cabo',                      array['Bíceps'],                              array['Cabo'],                   'beginner'),
('Concentration Curl',         'Rosca Concentrada',                  array['Bíceps'],                              array['Halteres'],               'beginner'),
('Preacher Curl',              'Rosca Scott com Barra',              array['Bíceps'],                              array['Barra','Máquina'],        'beginner'),
('Alternating Dumbbell Curl',  'Rosca Alternada com Haltere',        array['Bíceps'],                              array['Halteres'],               'beginner'),
('Reverse Curl',               'Rosca Inversa',                      array['Bíceps','Antebraços'],                 array['Barra'],                  'beginner'),
('Spider Curl',                'Rosca Aranha',                       array['Bíceps'],                              array['Barra','Banco'],          'intermediate'),
('Cable Hammer Curl',          'Rosca Martelo no Cabo',              array['Bíceps','Antebraços'],                 array['Cabo'],                   'beginner'),
('Machine Curl',               'Rosca na Máquina',                   array['Bíceps'],                              array['Máquina'],                'beginner'),
('Cross-body Curl',            'Rosca Cross-body',                   array['Bíceps','Antebraços'],                 array['Halteres'],               'beginner'),
('Barbell 21s',                '21s com Barra',                      array['Bíceps'],                              array['Barra'],                  'intermediate'),
('Drag Curl',                  'Rosca Drag',                         array['Bíceps'],                              array['Barra'],                  'intermediate'),
('Zottman Curl',               'Rosca Zottman',                      array['Bíceps','Antebraços'],                 array['Halteres'],               'intermediate'),
('High Cable Curl',            'Rosca no Cabo Alto',                 array['Bíceps'],                              array['Cabo'],                   'beginner'),

-- ► TRÍCEPS
('Tricep Dips',                'Tríceps no Banco / Paralela',        array['Tríceps','Peito'],                     array['Paralela','Banco'],       'intermediate'),
('Skull Crusher',              'Tríceps Testa',                      array['Tríceps'],                             array['Barra','Banco'],          'intermediate'),
('Tricep Pushdown',            'Tríceps no Pulley',                  array['Tríceps'],                             array['Cabo'],                   'beginner'),
('Overhead Tricep Extension',  'Tríceps Francês',                    array['Tríceps'],                             array['Halteres'],               'beginner'),
('Diamond Push-up',            'Flexão Diamante',                    array['Tríceps','Peito'],                     array['Peso Corporal'],          'intermediate'),
('Tricep Kickback',            'Tríceps Coice',                      array['Tríceps'],                             array['Halteres'],               'beginner'),
('Rope Pushdown',              'Tríceps no Pulley com Corda',        array['Tríceps'],                             array['Cabo'],                   'beginner'),
('Single-arm Cable Extension', 'Extensão de Tríceps Unilateral',     array['Tríceps'],                             array['Cabo'],                   'beginner'),
('Bench Dips',                 'Mergulho no Banco',                  array['Tríceps','Peito'],                     array['Banco'],                  'beginner'),
('Close-grip Push-up',         'Flexão com Mãos Fechadas',           array['Tríceps','Peito'],                     array['Peso Corporal'],          'beginner'),
('JM Press',                   'JM Press',                           array['Tríceps'],                             array['Barra','Banco'],          'advanced'),
('Lying Tricep Extension',     'Extensão de Tríceps Deitado (Cabo)', array['Tríceps'],                             array['Cabo','Banco'],           'beginner'),
('Tate Press',                 'Tate Press',                         array['Tríceps'],                             array['Halteres','Banco'],       'intermediate'),

-- ► PERNAS
('Barbell Back Squat',         'Agachamento com Barra',              array['Quadríceps','Glúteos','Isquiotibiais'],array['Barra'],                  'intermediate'),
('Romanian Deadlift',          'Stiff / Terra Romeno',               array['Isquiotibiais','Glúteos','Lombar'],    array['Barra'],                  'intermediate'),
('Leg Press',                  'Leg Press 45°',                      array['Quadríceps','Glúteos'],                array['Máquina'],                'beginner'),
('Walking Lunge',              'Avanço Caminhando',                  array['Quadríceps','Glúteos'],                array['Halteres'],               'beginner'),
('Leg Curl',                   'Flexão de Joelho (mesa flexora)',    array['Isquiotibiais'],                       array['Máquina'],                'beginner'),
('Leg Extension',              'Extensão de Joelho',                 array['Quadríceps'],                          array['Máquina'],                'beginner'),
('Hip Thrust',                 'Elevação Pélvica com Barra',         array['Glúteos','Isquiotibiais'],             array['Barra','Banco'],          'intermediate'),
('Calf Raise',                 'Panturrilha em Pé',                  array['Panturrilhas'],                        array['Máquina','Peso Corporal'],'beginner'),
('Bulgarian Split Squat',      'Agachamento Búlgaro',                array['Quadríceps','Glúteos'],                array['Halteres','Banco'],       'intermediate'),
('Sumo Squat',                 'Agachamento Sumô',                   array['Quadríceps','Glúteos','Adutores'],     array['Halteres'],               'beginner'),
('Goblet Squat',               'Agachamento Goblet',                 array['Quadríceps','Glúteos'],                array['Halteres'],               'beginner'),
('Hack Squat',                 'Hack Squat (Máquina)',               array['Quadríceps','Glúteos'],                array['Máquina'],                'intermediate'),
('Smith Machine Squat',        'Agachamento no Smith',               array['Quadríceps','Glúteos'],                array['Smith'],                  'beginner'),
('Seated Leg Curl',            'Flexão de Joelho Sentado',           array['Isquiotibiais'],                       array['Máquina'],                'beginner'),
('Standing Leg Curl',          'Flexão de Joelho em Pé',             array['Isquiotibiais'],                       array['Máquina'],                'beginner'),
('Abductor Machine',           'Cadeira Abdutora',                   array['Glúteos','Abdutores'],                 array['Máquina'],                'beginner'),
('Adductor Machine',           'Cadeira Adutora',                    array['Adutores'],                            array['Máquina'],                'beginner'),
('Seated Calf Raise',          'Panturrilha Sentado',                array['Panturrilhas'],                        array['Máquina'],                'beginner'),
('Step-up',                    'Subida no Banco',                    array['Quadríceps','Glúteos'],                array['Halteres','Banco'],       'beginner'),
('Glute Kickback',             'Kickback de Glúteos',                array['Glúteos'],                             array['Cabo','Peso Corporal'],   'beginner'),
('Reverse Lunge',              'Avanço Reverso',                     array['Quadríceps','Glúteos'],                array['Halteres'],               'beginner'),
('Lateral Lunge',              'Avanço Lateral',                     array['Quadríceps','Adutores','Glúteos'],     array['Peso Corporal'],          'beginner'),
('Glute Bridge',               'Ponte de Glúteos',                   array['Glúteos','Isquiotibiais'],             array['Peso Corporal'],          'beginner'),
('Single-leg Deadlift',        'Terra Unilateral (Pistol DL)',       array['Isquiotibiais','Glúteos','Lombar'],    array['Halteres'],               'advanced'),
('Front Squat',                'Agachamento Frontal',                array['Quadríceps','Glúteos'],                array['Barra'],                  'advanced'),
('Box Squat',                  'Agachamento na Caixa',               array['Quadríceps','Glúteos'],                array['Barra'],                  'intermediate'),
('Zercher Squat',              'Agachamento Zercher',                array['Quadríceps','Glúteos','Costas'],       array['Barra'],                  'advanced'),
('Sissy Squat',                'Agachamento Sissy',                  array['Quadríceps'],                          array['Peso Corporal'],          'intermediate'),
('Wall Sit',                   'Cadeira na Parede',                  array['Quadríceps','Glúteos'],                array['Peso Corporal'],          'beginner'),
('Nordic Curl',                'Flexão Nórdica',                     array['Isquiotibiais'],                       array['Peso Corporal'],          'advanced'),
('Cable Kickback',             'Kickback no Cabo',                   array['Glúteos'],                             array['Cabo'],                   'beginner'),
('Standing Hip Abduction',     'Abdução de Quadril em Pé',           array['Glúteos','Abdutores'],                 array['Cabo'],                   'beginner'),
('Curtsy Lunge',               'Avanço Cruzado',                     array['Glúteos','Quadríceps','Adutores'],     array['Halteres'],               'beginner'),
('Frog Pump',                  'Frog Pump',                          array['Glúteos'],                             array['Peso Corporal'],          'beginner'),
('Donkey Kick',                'Coice de Burro',                     array['Glúteos'],                             array['Peso Corporal'],          'beginner'),
('Fire Hydrant',               'Abdução de Quadril no Chão',         array['Glúteos','Abdutores'],                 array['Peso Corporal'],          'beginner'),
('Monster Walk',               'Caminhada com Elástico',             array['Glúteos','Abdutores'],                 array['Elástico'],               'beginner'),
('45° Back Extension',         'Hiperextensão 45° (Banco Romano)',   array['Lombar','Glúteos'],                    array['Máquina'],                'beginner'),
('Leg Press (pé fechado)',      'Leg Press com Pés Fechados',         array['Quadríceps'],                          array['Máquina'],                'beginner'),

-- ► ANTEBRAÇOS / GRIP
('Wrist Curl',                 'Flexão de Punho',                    array['Antebraços'],                          array['Barra'],                  'beginner'),
('Reverse Wrist Curl',         'Extensão de Punho',                  array['Antebraços'],                          array['Barra'],                  'beginner'),
('Plate Pinch',                'Pinça com Anilha',                   array['Antebraços','Grip'],                   array['Anilhas'],                'beginner'),
('Fat Bar Curl',               'Rosca com Barra Grossa',             array['Bíceps','Antebraços'],                 array['Barra'],                  'intermediate'),

-- ► CORE / ABDÔMEN
('Plank',                      'Prancha Isométrica',                 array['Abdômen','Lombar'],                    array['Peso Corporal'],          'beginner'),
('Crunch',                     'Abdominal Crunch',                   array['Abdômen'],                             array['Peso Corporal'],          'beginner'),
('Russian Twist',              'Abdominal Russo',                    array['Abdômen','Oblíquos'],                  array['Peso Corporal'],          'beginner'),
('Cable Crunch',               'Abdominal no Cabo',                  array['Abdômen'],                             array['Cabo'],                   'intermediate'),
('Hanging Leg Raise',          'Elevação de Pernas na Barra',        array['Abdômen','Quadríceps'],                array['Barra Fixa'],             'intermediate'),
('Side Plank',                 'Prancha Lateral',                    array['Oblíquos','Abdômen'],                  array['Peso Corporal'],          'beginner'),
('Bicycle Crunch',             'Abdominal Bicicleta',                array['Abdômen','Oblíquos'],                  array['Peso Corporal'],          'beginner'),
('V-Up',                       'Tesoura em V',                       array['Abdômen'],                             array['Peso Corporal'],          'intermediate'),
('Mountain Climber',           'Escalador',                          array['Abdômen','Cardio'],                    array['Peso Corporal'],          'intermediate'),
('Ab Wheel Rollout',           'Abdominal com Roda',                 array['Abdômen','Lombar'],                    array['Roda de Abdominal'],      'advanced'),
('Lying Leg Raise',            'Elevação de Pernas Deitado',         array['Abdômen'],                             array['Peso Corporal'],          'beginner'),
('Pallof Press',               'Pallof Press',                       array['Abdômen','Oblíquos'],                  array['Cabo'],                   'intermediate'),
('Dead Bug',                   'Dead Bug',                           array['Abdômen','Lombar'],                    array['Peso Corporal'],          'beginner'),
('Toe Touch',                  'Abdominal Toque no Pé',              array['Abdômen'],                             array['Peso Corporal'],          'beginner'),
('Dragon Flag',                'Dragon Flag',                        array['Abdômen','Lombar'],                    array['Banco'],                  'advanced'),
('Copenhagen Plank',           'Prancha de Copenhague',              array['Adutores','Oblíquos','Abdômen'],       array['Peso Corporal'],          'advanced'),
('Hollow Body Hold',           'Prancha Hollow Body',                array['Abdômen','Lombar'],                    array['Peso Corporal'],          'intermediate'),
('L-sit',                      'L-sit',                              array['Abdômen','Quadríceps'],                array['Paralela'],               'advanced'),
('Flutter Kicks',              'Bicicleta Deitada',                  array['Abdômen'],                             array['Peso Corporal'],          'beginner'),
('Windshield Wipers',          'Limpador de Para-brisa',             array['Oblíquos','Abdômen'],                  array['Barra Fixa'],             'advanced'),
('Cable Wood Chop',            'Corte de Lenha no Cabo',             array['Oblíquos','Abdômen'],                  array['Cabo'],                   'intermediate'),
('Weighted Crunch',            'Abdominal com Peso',                 array['Abdômen'],                             array['Anilhas'],                'beginner'),
('Stability Ball Crunch',      'Abdominal na Bola Suíça',            array['Abdômen'],                             array['Bola Suíça'],             'beginner'),
('Toe-to-Bar',                 'Toca-barra (Pés à Barra)',           array['Abdômen','Quadríceps'],                array['Barra Fixa'],             'advanced'),

-- ► CARDIO / FUNCIONAL / MÁQUINAS
('Burpee',                     'Burpee',                             array['Cardio'],                              array['Peso Corporal'],          'intermediate'),
('Box Jump',                   'Salto na Caixa',                     array['Quadríceps','Glúteos','Cardio'],       array['Peso Corporal'],          'intermediate'),
('Battle Rope',                'Corda de Batalha',                   array['Ombros','Cardio'],                     array['Elástico'],               'intermediate'),
('Jump Rope',                  'Pular Corda',                        array['Cardio','Panturrilhas'],               array['Corda'],                  'beginner'),
('Jumping Jacks',              'Polichinelo',                        array['Cardio'],                              array['Peso Corporal'],          'beginner'),
('Squat Jump',                 'Agachamento com Salto',              array['Quadríceps','Glúteos','Cardio'],       array['Peso Corporal'],          'intermediate'),
('Kettlebell Swing',           'Swing com Kettlebell',               array['Glúteos','Isquiotibiais','Cardio'],    array['Kettlebell'],             'intermediate'),
('Farmer Walk',                'Caminhada do Agricultor',            array['Antebraços','Trapézio','Cardio'],      array['Halteres'],               'beginner'),
('Turkish Get-up',             'Turkish Get-up',                     array['Ombros','Abdômen','Cardio'],           array['Kettlebell'],             'advanced'),
('Sled Push',                  'Empurrão no Trenó',                  array['Quadríceps','Glúteos','Cardio'],       array['Trenó'],                  'intermediate'),
('Bear Crawl',                 'Engatinhamento do Urso',             array['Abdômen','Ombros','Cardio'],           array['Peso Corporal'],          'intermediate'),
('Tuck Jump',                  'Salto com Joelhos ao Peito',         array['Cardio','Quadríceps'],                 array['Peso Corporal'],          'intermediate'),
('Treadmill',                  'Esteira',                            array['Cardio'],                              array['Esteira'],                'beginner'),
('Stationary Bike',            'Bicicleta Ergométrica',              array['Cardio','Quadríceps'],                 array['Bicicleta'],              'beginner'),
('Rowing Machine',             'Remo Ergométrico',                   array['Cardio','Costas','Bíceps'],            array['Ergômetro'],              'intermediate'),
('Elliptical',                 'Elíptico',                           array['Cardio'],                              array['Elíptico'],               'beginner'),
('Assault Bike',               'Bike de Assalto (Air Bike)',         array['Cardio'],                              array['Air Bike'],               'intermediate'),
('High Knees',                 'Corrida no Lugar (Joelhos Altos)',   array['Cardio'],                              array['Peso Corporal'],          'beginner'),
('Wall Ball',                  'Arremesso na Parede (Wall Ball)',    array['Cardio','Quadríceps','Ombros'],        array['Medicine Ball'],          'intermediate'),
('Thruster',                   'Thruster (Agachamento + Press)',     array['Quadríceps','Ombros','Glúteos'],       array['Barra'],                  'advanced'),
('Rope Climb',                 'Subida na Corda',                    array['Costas','Bíceps','Antebraços'],        array['Corda'],                  'advanced'),
('Inchworm',                   'Lagarta',                            array['Abdômen','Ombros','Isquiotibiais'],    array['Peso Corporal'],          'beginner'),
('Sled Pull',                  'Puxada no Trenó',                    array['Costas','Bíceps','Cardio'],            array['Trenó'],                  'intermediate'),
('Sandbag Carry',              'Carregamento de Sandbag',            array['Antebraços','Trapézio','Cardio'],      array['Sandbag'],                'intermediate'),
('Medicine Ball Slam',         'Arremesso de Medicine Ball no Chão', array['Abdômen','Ombros','Cardio'],           array['Medicine Ball'],          'intermediate'),
('Kettlebell Turkish Get-up',  'Turkish Get-up com Kettlebell',      array['Ombros','Abdômen','Cardio'],           array['Kettlebell'],             'advanced'),
('Kettlebell Clean',           'Clean com Kettlebell',               array['Glúteos','Costas','Ombros'],           array['Kettlebell'],             'advanced'),
('Kettlebell Press',           'Press com Kettlebell',               array['Ombros','Tríceps'],                    array['Kettlebell'],             'intermediate')

) as v(name, name_pt, muscle_groups, equipment, difficulty)
where not exists (
  select 1 from exercises e where e.name = v.name
);
