-- ============================================================
-- RESET TOTAL de contas de teste — usuário autorizou 2026-06-08.
-- JÁ EXECUTADA em produção em 2026-06-08.
--
-- NEUTRALIZADA em 2026-06-11: o corpo destrutivo foi comentado para
-- que o replay do chain de migrations em ambientes novos (db reset,
-- CI, staging) NÃO delete owners/academias criados pelas migrations
-- anteriores ou por seeds. Editar migration aplicada é proibido para
-- mudanças de SCHEMA (drift); aqui é DML one-time sem efeito de
-- schema — o estado de prod não muda com esta edição.
--
-- Corpo original preservado abaixo para referência:
-- ============================================================

-- delete from academies
-- where owner_id in (
--   select id from auth.users
--   where raw_user_meta_data->>'account_type' = 'owner'
-- );
--
-- delete from academy_members
-- where academy_id not in (select id from academies);
--
-- delete from auth.users
-- where raw_user_meta_data->>'account_type' = 'owner';
--
-- do $$
-- declare
--   n_owners int; n_academies int; n_members int;
-- begin
--   select count(*) into n_owners from auth.users where raw_user_meta_data->>'account_type' = 'owner';
--   select count(*) into n_academies from academies;
--   select count(*) into n_members from academy_members;
--   raise notice '=== RESET COMPLETO: owners=% academies=% members=% ===',
--     n_owners, n_academies, n_members;
-- end $$;

select 1; -- no-op: mantém o arquivo como migration válida no chain
